In [25]:
import numpy as np
import pandas as pd
import locale

In [2]:
df = pd.read_csv('./listings.csv')
df.head()

C:\Users\Jan\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,35303,https://www.airbnb.com/rooms/35303,20200322040935,2020-03-22,"La Casa Gaienmae C Harajuku, Omotesando is nearby",This shared flat is locating at very close to ...,This apartment is 3 bedroom flat shared with t...,This shared flat is locating at very close to ...,none,10 min walking to Harajuku ~ Urahara ~ Omotesa...,...,f,f,strict_14_with_grace_period,f,f,3,2,1,0,0.18
1,197677,https://www.airbnb.com/rooms/197677,20200322040935,2020-03-22,Oshiage Holiday Apartment,NaN,"We are happy to welcome you to our apartment, ...","We are happy to welcome you to our apartment, ...",none,NaN,...,f,f,moderate,f,f,1,1,0,0,1.59
2,289597,https://www.airbnb.com/rooms/289597,20200322040935,2020-03-22,Private apt in central Tokyo #203,NaN,::::::::::::::::::::::::::::::::::::::::::::::...,::::::::::::::::::::::::::::::::::::::::::::::...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,2,2,0,0,1.19
3,370759,https://www.airbnb.com/rooms/370759,20200322040935,2020-03-22,"Cozy flat #203, local area YET 10 mins to shib...","So close to busy centers, yet so peaceful! Jus...","Cozy and Relaxing, at home feeling in a reside...","So close to busy centers, yet so peaceful! Jus...",none,Peaceful and residential area just 10 mins awa...,...,t,f,strict_14_with_grace_period,f,f,3,3,0,0,1.40
4,700253,https://www.airbnb.com/rooms/700253,20200322040935,2020-03-22,Private apt in central Tokyo #201,NaN,::::::::::::::::::::::::::::::::::::::::::::::...,::::::::::::::::::::::::::::::::::::::::::::::...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,2,2,0,0,1.14

In [5]:
cal = pd.read_csv('./calendar.csv')
cal.head()

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,2645582,2020-03-22,f,"$10,500.00","$10,500.00",2,1125
1,2645582,2020-03-23,f,"$10,500.00","$10,500.00",2,1125
2,2645582,2020-03-24,f,"$10,500.00","$10,500.00",2,1125
3,2645582,2020-03-25,t,"$10,500.00","$10,500.00",2,1125
4,2645582,2020-03-26,t,"$10,500.00","$10,500.00",2,1125

In [64]:
df['price_val'] = df.price.replace('[\$,]*','',regex=True).astype(float)
df['weekly_price_val'] = df.weekly_price.replace('[\$,]*','',regex=True).astype(float)
df['monthly_price_val'] = df.monthly_price.replace('[\$,]*','',regex=True).astype(float)

In [67]:
df.price_val.isnull().sum()

0

In [68]:
df.groupby('host_id').price_val.mean()

host_id
151977        7571.666667
341577        4210.500000
771694       19751.125000
918551       15291.000000
961324        3546.000000
964081       10970.000000
1111228      15014.500000
1160146       7119.250000
1174369       9973.000000
1181399       5319.000000
1196132      19945.000000
1258947       9603.333333
1295685      29031.200000
1306308       9751.000000
1517461       3509.000000
1573631       7313.333333
1932364       5429.000000
2008948       4432.000000
2610437       6538.000000
2931434       7535.000000
3078284      19945.000000
3145185       4469.333333
3268251      20351.333333
3667176      23269.500000
4267866      59946.000000
4626879      16510.214286
4799233       4598.500000
4838043       5100.620690
4839990       5540.000000
4847803      13429.800000
                 ...
337632629    15457.500000
337689088    20388.000000
337862134    10970.000000
338092010     6261.000000
338105829     4432.000000
338127923     3324.000000
338696128     5385.000000
338751685    17119.500000
338837535    17951.000000
338915770     7479.500000
339093164     9973.000000
339095271     9529.000000
339101354    70029.000000
339263512    11967.000000
339264560     5762.000000
339288076    11967.000000
339768828    26667.000000
339956773     7646.000000
339976431    13962.000000
340125585    19945.000000
340144167     8384.333333
340283854    36012.000000
340589680    15706.750000
340740878    29751.333333
340905589     5984.000000
341055885    19945.000000
341382455    17208.400000
341486623     4986.000000
341754858    69919.000000
341763186     4986.000000
Name: price_val, Length: 3752, dtype: float64